// AUTO-GENERATED by `wails generate module`. Do NOT edit by hand.
// This stub enables TypeScript to type-check before running `wails generate module`.
// After running the command, this file will be replaced with real bindings.

import type {
  dto_AccountResponse,
  dto_AccountSearchRequest,
  dto_AuthResponse,
  dto_ChangePasswordRequest,
  dto_DashboardRequest,
  dto_DashboardResponse,
  dto_DocumentDetailsResponse,
  dto_DocumentResponse,
  dto_DocumentSearchRequest,
  dto_InitialStockRequest,
  dto_LoginRequest,
  dto_LoginResponse,
  dto_MoveProductRequest,
  dto_Page,
  dto_PeopleDetailsResponse,
  dto_PeopleResponse,
  dto_PeopleSearchRequest,
  dto_PlaceResponse,
  dto_ProductResponse,
  dto_ProductSearchRequest,
  dto_SaveAccountRequest,
  dto_SaveDocumentRequest,
  dto_SavePeopleRequest,
  dto_SavePlaceRequest,
  dto_SaveProductRequest,
  dto_SetupAuthRequest,
  dto_StockResponse,
  dto_StockSearchRequest,
  dto_TxResponse,
  dto_TxSearchRequest,
  dto_UnitDataResponse,
} from '../../models'

export function IsSetupRequired(): Promise<boolean>
export function SetupAuth(req: dto_SetupAuthRequest): Promise<void>
export function Login(req: dto_LoginRequest): Promise<dto_LoginResponse>
export function ChangePassword(req: dto_ChangePasswordRequest): Promise<void>

export function CreateAccount(req: dto_SaveAccountRequest): Promise<dto_AccountResponse>
export function UpdateAccount(req: dto_SaveAccountRequest): Promise<dto_AccountResponse>
export function SearchAccounts(req: dto_AccountSearchRequest): Promise<dto_Page<dto_AccountResponse>>
export function GetAllAccounts(): Promise<Record<number, dto_AccountResponse>>

export function CreatePeople(req: dto_SavePeopleRequest): Promise<dto_PeopleResponse>
export function UpdatePeople(req: dto_SavePeopleRequest): Promise<dto_PeopleResponse>
export function SearchPeople(req: dto_PeopleSearchRequest): Promise<dto_Page<dto_PeopleResponse>>
export function GetAllCustomers(): Promise<dto_PeopleResponse[]>
export function GetAllSuppliers(): Promise<dto_PeopleResponse[]>
export function GetAllPeople(): Promise<dto_PeopleResponse[]>
export function GetPeopleDetails(id: number): Promise<dto_PeopleDetailsResponse>

export function CreateProduct(req: dto_SaveProductRequest): Promise<dto_ProductResponse>
export function UpdateProduct(req: dto_SaveProductRequest): Promise<dto_ProductResponse>
export function SearchProduct(req: dto_ProductSearchRequest): Promise<dto_Page<dto_ProductResponse>>
export function MoveProduct(req: dto_MoveProductRequest): Promise<void>

export function SearchTransactions(req: dto_TxSearchRequest): Promise<dto_Page<dto_TxResponse>>
export function GetUnitData(): Promise<dto_UnitDataResponse>

export function CreatePlace(req: dto_SavePlaceRequest): Promise<dto_PlaceResponse>
export function UpdatePlace(req: dto_SavePlaceRequest): Promise<dto_PlaceResponse>
export function GetAllPlaces(): Promise<dto_PlaceResponse[]>

export function GetStock(req: dto_StockSearchRequest): Promise<dto_Page<dto_StockResponse>>
export function AddInitialStock(req: dto_InitialStockRequest): Promise<void>

export function SavePurchaseOrder(req: dto_SaveDocumentRequest): Promise<dto_DocumentResponse>
export function SaveInvoice(req: dto_SaveDocumentRequest): Promise<dto_DocumentResponse>

export function SearchDocuments(req: dto_DocumentSearchRequest): Promise<dto_Page<dto_DocumentResponse>>
export function GetDocumentDetails(id: number): Promise<dto_DocumentDetailsResponse>

export function GetDashboard(req: dto_DashboardRequest): Promise<dto_DashboardResponse>
