import '@testing-library/jest-dom'

// Mock the Wails runtime so tests run in jsdom without a Wails backend.
vi.mock('../src/wailsjs/go/main/App', () => ({
  IsSetupRequired: vi.fn().mockResolvedValue(false),
  SetupAuth: vi.fn().mockResolvedValue(undefined),
  Login: vi.fn().mockResolvedValue({ success: true, message: 'ok' }),
  ChangePassword: vi.fn().mockResolvedValue(undefined),
  CreateAccount: vi.fn().mockResolvedValue({ id: 1, accountName: 'Test', balance: '0' }),
  UpdateAccount: vi.fn().mockResolvedValue({ id: 1, accountName: 'Test', balance: '0' }),
  SearchAccounts: vi.fn().mockResolvedValue({ content: [], totalElements: 0, totalPages: 0, size: 20, number: 0 }),
  GetAllAccounts: vi.fn().mockResolvedValue({}),
  CreatePeople: vi.fn().mockResolvedValue({ id: 1, name: 'Test', contactNoList: [] }),
  UpdatePeople: vi.fn().mockResolvedValue({ id: 1, name: 'Test', contactNoList: [] }),
  SearchPeople: vi.fn().mockResolvedValue({ content: [], totalElements: 0, totalPages: 0, size: 20, number: 0 }),
  GetAllCustomers: vi.fn().mockResolvedValue([]),
  GetAllSuppliers: vi.fn().mockResolvedValue([]),
  GetAllPeople: vi.fn().mockResolvedValue([]),
  GetPeopleDetails: vi.fn().mockResolvedValue({ people: { id: 1, name: 'Test', contactNoList: [] }, transactions: [] }),
  CreateProduct: vi.fn().mockResolvedValue({ id: 1, name: 'Test' }),
  UpdateProduct: vi.fn().mockResolvedValue({ id: 1, name: 'Test' }),
  SearchProduct: vi.fn().mockResolvedValue({ content: [], totalElements: 0, totalPages: 0, size: 20, number: 0 }),
  MoveProduct: vi.fn().mockResolvedValue(undefined),
  SearchTransactions: vi.fn().mockResolvedValue({ content: [], totalElements: 0, totalPages: 0, size: 20, number: 0 }),
  GetUnitData: vi.fn().mockResolvedValue({ units: [{ id: 1, name: 'pcs' }], conversions: [] }),
  CreatePlace: vi.fn().mockResolvedValue({ id: 1, name: 'Test', address: '' }),
  UpdatePlace: vi.fn().mockResolvedValue({ id: 1, name: 'Test', address: '' }),
  GetAllPlaces: vi.fn().mockResolvedValue([]),
  GetStock: vi.fn().mockResolvedValue({ content: [], totalElements: 0, totalPages: 0, size: 20, number: 0 }),
  AddInitialStock: vi.fn().mockResolvedValue(undefined),
  SavePurchaseOrder: vi.fn().mockResolvedValue({ id: 1, total: '0', type: 'PURCHASE_ORDER' }),
  SaveInvoice: vi.fn().mockResolvedValue({ id: 1, total: '0', type: 'INVOICE' }),
  SearchDocuments: vi.fn().mockResolvedValue({ content: [], totalElements: 0, totalPages: 0, size: 20, number: 0 }),
  GetDocumentDetails: vi.fn().mockResolvedValue({ id: 1, items: [], payments: [] }),
  GetDashboard: vi.fn().mockResolvedValue({
    totalAccountBalance: '0', totalReceivable: '0', totalPayable: '0',
    topProductsByProfit: [], topProductsByQuantity: [], recentTransactions: [],
  }),
}))
