## default connection pool
spring.datasource.hikari.connectionTimeout=20000
spring.datasource.hikari.maximumPoolSize=5

## PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/shop
spring.datasource.username=postgres
spring.datasource.password=bolod2347

#drop n create table again, good for testing, comment this in production
spring.jpa.hibernate.ddl-auto=update


# 2 property for hibernate stats...
spring.jpa.properties.hibernate.generate_statistics = true
spring.jpa.properties.hibernate.stat = DEBUG
