// AUTO-GENERATED by Wails. Do NOT edit.
export function WindowSetTitle(title: string): void
export function WindowMinimise(): void
export function WindowMaximise(): void
export function WindowClose(): void
export function BrowserOpenURL(url: string): void
export function EventsOn(eventName: string, callback: (...data: any[]) => void): void
export function EventsOff(eventName: string): void
export function EventsEmit(eventName: string, ...data: any[]): void
