// AUTO-GENERATED by `wails generate module`. Do NOT edit by hand.
// Stub types to enable development before running `wails generate module`.

export interface dto_Page<T> {
  content: T[]
  totalElements: number
  totalPages: number
  size: number
  number: number
}

export interface dto_AccountResponse {
  id: number
  type: string
  accountName: string
  holderName: string
  bank: string
  branch: string
  accountNo: string
  balance: string
}

export interface dto_SaveAccountRequest {
  id?: number
  type: string
  accountName: string
  holderName: string
  bank?: string
  branch?: string
  accountNo: string
  balance?: string
}

export interface dto_AccountSearchRequest {
  page: number
  size: number
  accountNo?: string
  accountName?: string
  holderName?: string
}

export interface dto_ContactNoDTO {
  id?: number
  no: string
}

export interface dto_PeopleResponse {
  id: number
  name: string
  companyName: string
  address: string
  type: string
  email: string
  balance: string
  contactNoList: dto_ContactNoDTO[]
}

export interface dto_SavePeopleRequest {
  id?: number
  name: string
  companyName: string
  address?: string
  type: string
  email?: string
  contactNoList: dto_ContactNoDTO[]
}

export interface dto_PeopleSearchRequest {
  page: number
  size: number
  name?: string
  companyName?: string
  type?: string
}

export interface dto_PeopleDetailsResponse {
  people: dto_PeopleResponse
  transactions: dto_TxResponse[]
}

export interface dto_ProductResponse {
  id: number
  name: string
  type: string
  brand: string
  country: string
  size: string
  preferredUnit: number
}

export interface dto_SaveProductRequest {
  id?: number
  name: string
  type?: string
  brand?: string
  country: string
  size?: string
  preferredUnit: number
}

export interface dto_ProductSearchRequest {
  page: number
  size: number
  name?: string
  type?: string
  brand?: string
  country?: string
  size?: string
}

export interface dto_MoveProductRequest {
  productId: number
  fromPlaceId: number
  toPlaceId: number
  quantity: string
  unitId: number
}

export interface dto_TxResponse {
  id: number
  amount: string
  fromAccountId: number
  fromAccount?: dto_AccountResponse
  toAccountId: number
  toAccount?: dto_AccountResponse
  documentId: number
  peopleId: number
  people?: dto_PeopleResponse
  ref: string
  type: string
  description: string
  createdAt: string
}

export interface dto_TxSearchRequest {
  page: number
  size: number
  type?: string
  peopleId?: number
  accountId?: number
  documentId?: number
  dateFrom?: string
  dateTo?: string
}

export interface dto_PlaceResponse {
  id: number
  name: string
  address: string
}

export interface dto_SavePlaceRequest {
  id?: number
  name: string
  address: string
}

export interface dto_StockResponse {
  id: number
  productId: number
  product?: dto_ProductResponse
  cost: string
  latestPrice: string
  quantity: string
  unitId: number
  unit?: dto_UnitDTO
  placeId: number
  place?: dto_PlaceResponse
}

export interface dto_StockSearchRequest {
  page: number
  size: number
  productId?: number
  placeId?: number
}

export interface dto_InitialStockRequest {
  productId: number
  placeId: number
  unitId: number
  quantity: string
  cost: string
}

export interface dto_DocumentItemInput {
  productId: number
  quantity: string
  cost: string
  price?: string
  unitId: number
  placeId: number
}

export interface dto_PaymentInput {
  amount: string
  fromAccount?: number
  toAccount?: number
}

export interface dto_SaveDocumentRequest {
  peopleId: number
  items: dto_DocumentItemInput[]
  payments: dto_PaymentInput[]
}

export interface dto_DocumentResponse {
  id: number
  peopleId: number
  people?: dto_PeopleResponse
  type: string
  total: string
  profit: string
  createdAt: string
}

export interface dto_DocumentItemResponse {
  id: number
  productId: number
  product?: dto_ProductResponse
  quantity: string
  cost: string
  price: string
  unitId: number
  placeId: number
}

export interface dto_DocumentDetailsResponse extends dto_DocumentResponse {
  items: dto_DocumentItemResponse[]
  payments: dto_TxResponse[]
}

export interface dto_DocumentSearchRequest {
  page: number
  size: number
  type?: string
  peopleId?: number
  dateFrom?: string
  dateTo?: string
}

export interface dto_UnitDTO {
  id: number
  name: string
}

export interface dto_UnitConversionDTO {
  id: number
  from: number
  to: number
  calStep: number
  operator: string
  constant: string
}

export interface dto_UnitDataResponse {
  units: dto_UnitDTO[]
  conversions: dto_UnitConversionDTO[]
}

export interface dto_DashboardRequest {
  dateFrom?: string
  dateTo?: string
}

export interface dto_ChartPoint {
  label: string
  value: string
}

export interface dto_DashboardResponse {
  totalReceivable: string
  totalPayable: string
  totalAccountBalance: string
  topProductsByProfit: dto_ChartPoint[]
  topProductsByQuantity: dto_ChartPoint[]
  recentTransactions: dto_TxResponse[]
}

export interface dto_SetupAuthRequest {
  password: string
}

export interface dto_LoginRequest {
  password: string
}

export interface dto_LoginResponse {
  success: boolean
  message: string
}

export interface dto_ChangePasswordRequest {
  oldPassword: string
  newPassword: string
}

export type dto_AuthResponse = dto_LoginResponse

export interface dto_ActivateLicenseRequest {
  key: string
}

export interface dto_LicenseStatusResponse {
  status: string        // "none" | "valid" | "expired"
  type: string          // "standard" | "professional" | "enterprise"
  seats: number
  expiresAt: string     // ISO date string
  daysRemaining: number // negative = already expired
  key: string           // masked key for display
}
